# Generated by Django 3.2.16 on 2023-01-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='AuthorModel',
        ),
    ]
